### ISSUE TITLE
Unhelpful error message on syntax error

### ISSUE THREAD

**Issue by zbyte64** [ryanseddon/gulp-es6-module-transpiler#26]
So let's say I have a gulp file::

    gulp.task('default', function() {
      return gulp.src('clients/**/*.jsx')
        .pipe(react())
        .pipe(transpile({
          formatter: 'commonjs'
        }))
        .pipe(gulp.dest('dist'))
    });

And we run gulp only to find the following error message::

    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: Line 111: Unexpected token =
        at throwError (/home/jason/Repos/django-montage/node_modules/gulp-es6-module-transpiler/node_modules/es6-module-transpiler/node_modules/esprima-fb/esprima.js:2417:21)
        at throwUnexpected (/home/jason/Repos/django-montage/node_modules/gulp-es6-module-transpiler/node_modules/es6-module-transpiler/node_modules/esprima-fb/esprima.js:2479:9)
        at parsePrimaryExpression (/home/jason/Repos/django-montage/node_modules/gulp-es6-module-transpiler/node_modules/es6-module-transpiler/node_modules/esprima-fb/esprima.js:3120:9)
        at parseLeftHandSideExpressionAllowCall (/home/jason/Repos/django-montage/node_modules/gulp-es6-module-transpiler/node_modules/es6-module-transpiler/node_modules/esprima-fb/esprima.js:3201:61)
        at parsePostfixExpression (/home/jason/Repos/django-montage/node_modules/gulp-es6-module-transpiler/node_modules/es6-module-transpiler/node_modules/esprima-fb/esprima.js:3241:20)
        at parseUnaryExpression (/home/jason/Repos/django-montage/node_modules/gulp-es6-module-transpiler/node_modules/es6-module-transpiler/node_modules/esprima-fb/esprima.js:3308:16)
        at parseBinaryExpression (/home/jason/Repos/django-montage/node_modules/gulp-es6-module-transpiler/node_modules/es6-module-transpiler/node_modules/esprima-fb/esprima.js:3398:16)
        at parseConditionalExpression (/home/jason/Repos/django-montage/node_modules/gulp-es6-module-transpiler/node_modules/es6-module-transpiler/node_modules/esprima-fb/esprima.js:3458:16)
        at parseAssignmentExpression (/home/jason/Repos/django-montage/node_modules/gulp-es6-module-transpiler/node_modules/es6-module-transpiler/node_modules/esprima-fb/esprima.js:3697:16)
        at parseExportDeclaration (/home/jason/Repos/django-montage/node_modules/gulp-es6-module-transpiler/node_modules/es6-module-transpiler/node_modules/esprima-fb/esprima.js:4134:31)
        at parseProgramElement (/home/jason/Repos/django-montage/node_modules/gulp-es6-module-transpiler/node_modules/es6-module-transpiler/node_modules/esprima-fb/esprima.js:5493:24)

Some googling leads me to believe that this is caused by a syntax error in my code:
https://github.com/andreypopp/reactify/issues/14
https://github.com/SBoudrias/gulp-istanbul/issues/41

Which is strange because this code compiled just fine with grunt-es6-module-transpiler. I would just zero in on the offending code but the exception makes this finding a needle in a haystack. So what do I do next?

**Comment by ryanseddon** [comment]
Hard to say without seeing the code you're trying to compile. Can you provide an example that fails.

**Comment by janjakubnanista** [comment]
@zbyte64 Hi Jason, could you maybe try to have JSHint validate the javascript file?

**Comment by zbyte64** [comment]
My point is that a syntax error should at least tell you the filename. There is way too many LOCs for me to paste the source here, this is a large react project with multiple source files that compiles just fine with grunt-es6-module-transpiler - at least with that it would tell me the filename and line number of the offending syntax. 

I added JSHint to my gulp task and cleaned up some warnings, the only errors left are unnecessary semicolons.

I guess I will try running the task on each of my individual files to find this needle. But seriously, this error message is not as helpful as it should be.

**Comment by zbyte64** [comment]
Ended up switching to gulp-esperanto , everything worked.

**Comment by ryanseddon** [comment]
How about a PR instead of complaining, we all have jobs here and we do this in our free time. Your attitude isn't helpful.
